RouterFinder.Web/Models/ErrorViewModel.cs
using System;

namespace RouterFinder.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RouterFinder.Web/Models/Route.cs
using System;

namespace RouterFinder.Web.Models
{
    public class Route
    {
        public Guid Id { get; set; }
        public string routeFrom { get; set; }
        public string routeTo { get; set; }
        public double routeValue { get; set; }
    }
}

RouterFinder.Web/Models/RouteItem.cs
using System;

namespace RouterFinder.Web.Models
{
    public class RouteItem
    {
        public string Name { get; set; }
    }
}

RouterFinder.Web/Models/RouteUtil.cs
using Newtonsoft.Json;
using RestSharp;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RouterFinder.Web.Models
{
    public static class RouteUtil
    {
        // base url
        private static string baseUrl = "https://localhost:44305";
        
        public static async Task<List<Route>> getRoutes()
        {
            List<Route> routes = new List<Route>();
            var client = new RestClient($"{baseUrl}/api/routerFinder");
            var request = new RestRequest(Method.GET);
            IRestResponse response = await client.ExecuteAsync(request);
            routes = JsonConvert.DeserializeObject<List<Route>>(response.Content);
            return routes.OrderBy(x => x.routeFrom).ToList();
        }
    }
}

RouterFinder.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using RestSharp;
using RouterFinder.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using RouterFinder.Web.Models;

namespace RouterFinder.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            // get routes from api
            var routes =  await RouteUtil.getRoutes();

            // get all distincts from routes
            var startPoints = GetFromList(routes);

            ViewBag.StartPoints = new SelectList(startPoints, "Name", "Name");
            return View();
        }

        protected List<RouteItem> GetFromList(List<Route> rotas)
        {
            // get all distincts from routes
            List<RouteItem> fromList = new List<RouteItem>();
            foreach (var item in rotas)
            {
                // prevent duplicated items
                if (!fromList.Any(x => x.Name == item.routeFrom))
                    fromList.Add(new RouteItem { Name = item.routeFrom });
            }

            return fromList;
        }
    }
}

RouterFinder.Web/Controllers/RoutesController.cs
using Microsoft.AspNetCore.Mvc;
using RouterFinder.Web.Models;
using System.Threading.Tasks;

namespace RouterFinder.Web.Controllers
{
    public class RoutesController : Controller
    {
        public async Task<IActionResult> Index()
        {
            // get all routes from api
            var routes = await RouteUtil.getRoutes();
            return View(routes);
        }
    }
}

RouterFinder.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row pt-2 justify-content-center">
    <div class="col-10 pt-2">
        <div class="alert alert-primary shadow">
            <div class="card shadow">
                <div class="card-header">
                    <h2>
                        <i class="fas fa-plane me-1"></i>
                        Choose your destiny
                    </h2>
                </div>
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col">
                            <div class="form-control">
                                <label>From</label>
                                <select class="form-control" asp-items="(SelectList)ViewBag.StartPoints" id="selectFrom">
                                    <option>Select one</option>
                                </select>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-control">
                                <label>To</label>
                                <select class="form-control" id="selectTo">
                                    <option>Select one</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <span id="btnFind" class="btn btn-primary">
                                <i class="fas fa-globe-americas me-2"></i>
                                Find best route
                            </span>
                        </div>
                    </div>
                </div>
                <div class="card-footer ">
                    <div class="d-flex justify-content-between">
                        <h4>
                            <i class="fas fa-thumbs-up me-1"></i>
                            The best route for you...
                        </h4>
                        <h4>
                            <i class="fas fa-badge-dollar me-1"></i>
                            <span id="spanCost"></span>
                        </h4>
                    </div>
                    <div>
                        <ul class="list-group" id="listRoutes">
                            
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
<script src="~/js/home.js"></script>
}

RouterFinder.Web/Views/Routes/Index.cshtml
@model List<RouterFinder.Web.Models.Route>
@{
    ViewData["Title"] = "Index";
}
<div class="row justify-content-center mb-2 pt-2">
    <div class="col-10 col-lg-12 pt-2">
        <div class="alert alert-primary d-flex justify-content-between align-items-center">
            <h3>
                <i class="fas fa-map-marker-alt me-1"></i>
                List of all routes
            </h3>
            <span id="btShowModal" class="btn btn-primary">
                <i class="fas fa-route me-1"></i>
                new Route
            </span>
        </div>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-10 col-lg-12">
        <table class="table table-bordered shadow table-sm table-hover shadow">
            <thead>
                <tr>
                    <th class="thPrimary text-primary">From</th>
                    <th class="thPrimary text-primary">To</th>
                    <th class="thPrimary text-primary">Cost</th>
                    <th class="thPrimary text-primary" style="width: 130px">#</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var route in Model)
                {
                    <tr>
                        <td>@(route.routeFrom)</td>
                        <td>@(route.routeTo)</td>
                        <td>@(route.routeValue)</td>
                        <td class="text-center">
                            <span class="cursor text-primary" data-bs-toggle="modal" data-bs-target="#modalAdd" data-id="@(route.Id)" onclick="localStorage.setItem('idRoute', '@(route.Id)'); localStorage.setItem('op', 'edit'); document.getElementById('from').value='@(route.routeFrom)'; document.getElementById('to').value='@(route.routeTo)'; document.getElementById('cost').value='@(route.routeValue)'">
                                <i class="fas fa-edit me-1"></i>
                            </span>
                            <span class="cursor text-danger" data-bs-toggle="modal" data-bs-target="#modalRemove" data-id="@(route.Id)" onclick="localStorage.setItem('idRoute', '@(route.Id)');">
                                <i class="fas fa-trash ms-1"></i>
                            </span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<!--Modal Add-->
<div class="modal fade" id="modalAdd" tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary">
                    <i class="fas fa-route me-1"></i>
                    Add route

                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <form id="frmAdd">
                        <input id="typeOp" type="hidden" value="" />
                        <div class="row mb-1">
                            <div class="col-4">
                                <div class="form-group">
                                    <label for="from" class="">From</label>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-primary">
                                            <i class="fad fa-map-marked"></i>
                                        </span>
                                        <input type="text" class="form-control" id="from" placeholder="from">
                                    </div>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label for="from" class="text-primary">From</label>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-primary">
                                            <i class="fas fa-map-marked-alt"></i>
                                        </span>
                                        <input type="text" class="form-control" id="to" placeholder="to">
                                    </div>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label for="cost" class="text-primary">Cost</label>
                                    <input type="number" class="form-control" id="cost" placeholder="cost">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <a class="btn btn-secondary" asp-action="Index" data-bs-dismiss="modal">Close</a>
                <span class="btn btn-primary" id="btAdd">Save changes</span>
            </div>
        </div>
    </div>
</div>

<!--Modal Remove-->
<div class="modal fade" id="modalRemove" tabindex="-1">
    <div class="modal-dialog modal modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-danger">
                    <i class="fas fa-route me-1"></i>
                    Remove route
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-3 text-danger">
                <h4>Are you shure?</h4>
            </div>
            <div class="modal-footer">
                <button id="modalRemoveClose" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <span class="btn btn-danger" id="btRemove">Revove</span>
            </div>
        </div>
    </div>
</div>

@section scripts{
<script src="~/js/routes.js"></script>
}

RouterFinder.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RouterFinder.Web</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous" />
    <link href="https://cdn.staticaly.com/gh/hung1001/font-awesome-pro/4cac1a6/css/all.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-paper-plane"></i>
                    Router Finder
                    <i class="fas fa-bullseye-pointer"></i>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Routes" asp-action="Index">Routes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            <div class="d-flex justify-content-between">
                <div>
                    &copy; @DateTime.Now.Year -
                    <i class="fas fa-paper-plane"></i>
                    Router Finder
                    <i class="fas fa-bullseye-pointer"></i>
                </div>
                <div>
                    Develop by Wellington Rogério
                </div>
            </div>

        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>